sudo: required
dist: xenial
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
language: scala
scala:
- 2.12.9
jdk:
- openjdk8
stages:
- test
- formatting
- name: release
  if: tag =~ ^v
- name: snapshot
  if: "(NOT tag IS present) AND (type = push)"
jobs:
  include:
  - stage: test
    script: sbt scalafmtCheck coverage test && sbt coverageReport coverageAggregate
      coveralls
  - stage: formatting
    script: sbt scalafmtCheck
  - stage: release
    script: openssl aes-256-cbc -K $encrypted_98cf3af00429_key -iv $encrypted_98cf3af00429_iv
      -in ci/secring.asc.enc -out ci/secring.asc -d && gpg --import ci/secring.asc
      && sbt publishSigned sonatypeBundleRelease
  - stage: snapshot
    script: sbt publish
env:
  global:
  - secure: V71Yaxy7x4Mezu8TX8oYZCPXMob+Y3LBnqmciNVG4GaRq1mNyh5GpD/bnGphXEhhedDD7KoLJ2KZayn9HSh1aSuzGQOhRqoy+2uwDS2laVkS8+dcwuqy9VnDNV4qiSAqS/U0zg70dctnAjZJndo6hQqBPNlrYMW1THGftcsdYrJu79PrQ2audWRCfFbHrHCmXrkZORdqumk7G3CIR9wudrQXf2+hf+L1bFqFHYxV2UFln7K8aiabRxMS+GOOEakzpPsumBqEMvBvcuCLl8NcmGDP9I9r8MIilc9HK4rnPA6xvl+0f9axGTUP/k/XXCkYpHheWTs1KOHxHt5jwo2/9J1von+2VccRP0RNa8nCdKVlFdOUjid02ZCj8ruJ8AcBvC51vmmTi/cxIBiE7JIj6puZblQ8ktdwqQLEhmT458tRDR2w8fBcU1IyUUipng/9G4UEQqNmTcsLX1C9rLQH5JuX2gkLOuG1cmjI9Yi9v3Jvqi++NRvhkQ6seCwHtTdGIEYJzunPmIKcJP0mj11cYQExx0wV1xrUtkBhp0PXVFnITH52zr+RYWXGSuX0HxSgVsK+0XHZxUjNFlEGeCpqo5tPm5D0GSEO7O+up/A/7eqMHUGPXGuxInHYpmH2vyb2KVL7XQzDMtIW8wRkjXx71HDg2WQuqmhkWnak8fQri2E=
  - secure: fhE3wPh1LE49CI3XMQlt6WQqcUUA3E4TGlXKOsjfDk7ClCXgXDiob0TnjwjFs6cp6QMS1oCxAd5Qko4elZqCu7rjzfOqcYnNVVCOT2OKDYho23Sbh6f7ZKUsAHNYPZ7DtHvJ92u+Y3OOq/zHCR+1BWxRTE6Fhkl6G+PSrBL6/GFSPl3t/zhGCnVDa90ZKo144b1nszOC9bhMAnnUpGTRaP4odT2WTJg3jwk2IjOeLwmTBTuIf6cEvV4wdDtZ9HBgUvtKk0T+Lx3L6GIrYtGDQe8Z7FB6KpF0SsSMhc7Vq4PvbWyoBqc0bUhJV2kxESTaB8wgkWtmh/WKmdrN0Ba3MfltsAHpi3RBFp/ar/FRO+KSoa4ajkZgQq2ucaK6Evymuwx6eLuS6RKyKC/16kiFEt3exZOVXD3aQ2wTV9/RtaTAYUi1WuqZlhs3wOQmSdALS1cD8nRsg9wzHvgm0AoUC3tLCjhBUbeO2n0vf9nbFdIUz2TTQQQqU/E4b1roHB5AyzQCUuv1cIlPHi7gH2tw5aRSdnLJkUesmdPX3NXRDoTdO8mP86IWsIoSq+VToFpwx6+KT/8fRqqQ6cAhfrFKLpl/BkUC6YP/TZZ6GmaByrh0v2mTXJUMiz14BUQ2Xj/t1vy0q41KJlYsEDECC/1jGcP5hNubct3vLtyhv89QQyM=
