sudo: required
dist: xenial
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
language: scala
scala:
  - 2.12.9
jdk:
- openjdk8

stages:
- test
- name: release
  if: tag =~ ^v
- name: snapshot
  if: "(NOT tag IS present) AND (type = push)"
jobs:
  include:
  - stage: test
    script: sbt coverage test && sbt coverageReport coverageAggregate coveralls
  - stage: release
    # decrypt the private key (exported via https://docs.scala-lang.org/overviews/contributors/index.html#export-your-pgp-key-pair )
    script: openssl aes-256-cbc -K $encrypted_98cf3af00429_key -iv $encrypted_98cf3af00429_iv -in ci/secring.asc.enc -out ci/secring.asc -d && gpg --import ci/secring.asc && sbt -jvm-opts .travis.jvmopts publishSigned sonatypeBundleRelease
  - stage: snapshot
    script: sbt publish
